name: Automatic Versioning
author: discoverygarden
description: Updates the current version tag based on a provided label.

inputs:
  token:
    description: 'Token to use to push to the repo. Pass in using `secrets.GITHUB_TOKEN`.'
    required: true
  prefix:
    description: The prefix prepended to the version number. Default is v.
    required: false
    default: v

runs:
  using: "composite"
  steps:
    - env:
        ACTION_TOKEN: ${{ inputs.token }}
        ACTION_PREFIX: ${{ inputs.prefix }}
      id: bump
      #if: github.event.pull_request.merged == true
      uses: zwaldowski/match-label-action@v2
      with:
        allowed: major,minor,patch
    - name: 'Output Bump'
      run: echo "${{ steps.bump.outputs.match }}"
    - uses: zwaldowski/semver-release-action@v2
      #if: github.event.pull_request.merged == true
      with:
        bump: ${{ steps.bump.outputs.match }}
        github_token: $ACTION_TOKEN
        prefix: $ACTION_PREFIX
