name: Automatic Versioning
author: discoverygarden
description: Updates the current version tag based on a provided label.

inputs:
  token:
    description: 'Token to use to push to the repo. Pass in using `secrets.GITHUB_TOKEN`.'
    required: true
  prefix:
    description: The prefix prepended to the version number. Default is v.
    required: false
    default: v

runs:
  using: "composite"
  steps:
    - id: bump
      uses: zwaldowski/match-label-action@9e74bc4791a2b1b712d82fea03db1c5dd18ae514
      with:
        allowed: major,minor,patch
    - uses: zwaldowski/semver-release-action@239e9cd0db94c047ca49b554fd217386f0f86ad4
      with:
        bump: ${{ steps.bump.outputs.match }}
        github_token: ${{ inputs.token }}
        prefix: ${{ inputs.prefix }}
